### ISSUE TITLE
installLibrealsenseUVC.sh (Crash)

### ISSUE THREAD

**Issue by vftejada** [jetsonhacks/installLibrealsense#1]
Unable to install 'installLibrealsenseUVC.sh' shell file on a newly flashed Jetson TX1 using 64-bit JetPack 2.2. Got the following errors:

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at ac753ca... Merge pull request #207 from mdhorn/arm64-cflags
patching file Makefile
Hunk #1 FAILED at 12.
1 out of 1 hunk FAILED -- saving rejects to file Makefile.rej
patching file librealsense.qtcreator/realsense.pro
patching file src/image.cpp
Hunk #1 FAILED at 8.
Hunk #2 succeeded at 66 with fuzz 2 (offset 2 lines).
Hunk #3 succeeded at 449 with fuzz 2 (offset 243 lines).
1 out of 3 hunks FAILED -- saving rejects to file src/image.cpp.rej
patching file src/uvc-v4l2.cpp
Hunk #1 succeeded at 249 (offset 2 lines).
mkdir -p obj/libuvc
mkdir -p lib
mkdir -p bin
cc src/verify.c -std=c89 -Iinclude -c -o obj/verify.o
g++ src/context.cpp -std=c++11 -fPIC -pedantic -Ofast -Wno-missing-field-initializers -Wno-switch -Wno-multichar -DRS_USE_LIBUVC_BACKEND `pkg-config --cflags --libs libusb-1.0` -mfpu=neon -mfloat-abi=hard -ftree-vectorize -c -o obj/context.o
g++ src/device.cpp -std=c++11 -fPIC -pedantic -Ofast -Wno-missing-field-initializers -Wno-switch -Wno-multichar -DRS_USE_LIBUVC_BACKEND `pkg-config --cflags --libs libusb-1.0` -mfpu=neon -mfloat-abi=hard -ftree-vectorize -c -o obj/device.o
g++ src/f200-private.cpp -std=c++11 -fPIC -pedantic -Ofast -Wno-missing-field-initializers -Wno-switch -Wno-multichar -DRS_USE_LIBUVC_BACKEND `pkg-config --cflags --libs libusb-1.0` -mfpu=neon -mfloat-abi=hard -ftree-vectorize -c -o obj/f200-private.o
g++ src/f200.cpp -std=c++11 -fPIC -pedantic -Ofast -Wno-missing-field-initializers -Wno-switch -Wno-multichar -DRS_USE_LIBUVC_BACKEND `pkg-config --cflags --libs libusb-1.0` -mfpu=neon -mfloat-abi=hard -ftree-vectorize -c -o obj/f200.o
g++ src/image.cpp -std=c++11 -fPIC -pedantic -Ofast -Wno-missing-field-initializers -Wno-switch -Wno-multichar -DRS_USE_LIBUVC_BACKEND `pkg-config --cflags --libs libusb-1.0` -mfpu=neon -mfloat-abi=hard -ftree-vectorize -c -o obj/image.o
src/image.cpp: In function 'void rsimpl::unpack_yuy2(rsimpl::byte\* const_, const rsimpl::byte_, int)':
src/image.cpp:470:58: error: there are no arguments to 'clamp_byte' that depend on a template parameter, so a declaration of 'clamp_byte' must be available [-fpermissive]
     ptrOut[0] = clamp_byte((128 + 298 \* c + 409 \* e) >> 8); // red
                                                          ^
src/image.cpp:470:58: note: (if you use '-fpermissive', G++ will accept your code, but allowing the use of an undeclared name is deprecated)
src/image.cpp:471:68: error: there are no arguments to 'clamp_byte' that depend on a template parameter, so a declaration of 'clamp_byte' must be available [-fpermissive]
     ptrOut[1] = clamp_byte((128 + 298 \* c - 100 \* d - 208 \* e) >> 8); // green
                                                                    ^
src/image.cpp:472:58: error: there are no arguments to 'clamp_byte' that depend on a template parameter, so a declaration of 'clamp_byte' must be available [-fpermissive]
     ptrOut[2] = clamp_byte((128 + 298 \* c + 516 \* d) >> 8); // blue
                                                          ^
src/image.cpp:474:58: error: there are no arguments to 'clamp_byte' that depend on a template parameter, so a declaration of 'clamp_byte' must be available [-fpermissive]
     ptrOut[3] = clamp_byte((128 + 298 \* c + 409 \* e) >> 8); // red
                                                          ^
src/image.cpp:475:68: error: there are no arguments to 'clamp_byte' that depend on a template parameter, so a declaration of 'clamp_byte' must be available [-fpermissive]
     ptrOut[4] = clamp_byte((128 + 298 \* c - 100 \* d - 208 \* e) >> 8); // green
                                                                    ^
src/image.cpp:476:58: error: there are no arguments to 'clamp_byte' that depend on a template parameter, so a declaration of 'clamp_byte' must be available [-fpermissive]
     ptrOut[5] = clamp_byte((128 + 298 \* c + 516 \* d) >> 8); // blue
                                                          ^
src/image.cpp: In function 'void rsimpl::deproject_z(float_, const rs_intrinsics&, const uint16_t_, float)':
src/image.cpp:486:98: error: 'deproject_depth' was not declared in this scope
         deproject_depth(points, z_intrin, z_pixels, [z_scale](uint16_t z) { return z_scale \* z; });
                                                                                                  ^
src/image.cpp: In function 'void rsimpl::deproject_disparity(float_, const rs_intrinsics&, const uint16_t_, float)':
src/image.cpp:491:146: error: 'deproject_depth' was not declared in this scope
         deproject_depth(points, disparity_intrin, disparity_pixels, [disparity_scale](uint16_t disparity) { return disparity_scale / disparity; });
                                                                                                                                                  ^
make: **\* [obj/image.o] Error 1
mkdir -p obj/libuvc
mkdir -p lib
mkdir -p bin
g++ src/image.cpp -std=c++11 -fPIC -pedantic -Ofast -Wno-missing-field-initializers -Wno-switch -Wno-multichar -DRS_USE_V4L2_BACKEND `pkg-config --cflags --libs libusb-1.0` -mfpu=neon -mfloat-abi=hard -ftree-vectorize -c -o obj/image.o
src/image.cpp: In function 'void rsimpl::unpack_yuy2(rsimpl::byte\* const_, const rsimpl::byte_, int)':
src/image.cpp:470:58: error: there are no arguments to 'clamp_byte' that depend on a template parameter, so a declaration of 'clamp_byte' must be available [-fpermissive]
     ptrOut[0] = clamp_byte((128 + 298 \* c + 409 \* e) >> 8); // red
                                                          ^
src/image.cpp:470:58: note: (if you use '-fpermissive', G++ will accept your code, but allowing the use of an undeclared name is deprecated)
src/image.cpp:471:68: error: there are no arguments to 'clamp_byte' that depend on a template parameter, so a declaration of 'clamp_byte' must be available [-fpermissive]
     ptrOut[1] = clamp_byte((128 + 298 \* c - 100 \* d - 208 \* e) >> 8); // green
                                                                    ^
src/image.cpp:472:58: error: there are no arguments to 'clamp_byte' that depend on a template parameter, so a declaration of 'clamp_byte' must be available [-fpermissive]
     ptrOut[2] = clamp_byte((128 + 298 \* c + 516 \* d) >> 8); // blue
                                                          ^
src/image.cpp:474:58: error: there are no arguments to 'clamp_byte' that depend on a template parameter, so a declaration of 'clamp_byte' must be available [-fpermissive]
     ptrOut[3] = clamp_byte((128 + 298 \* c + 409 \* e) >> 8); // red
                                                          ^
src/image.cpp:475:68: error: there are no arguments to 'clamp_byte' that depend on a template parameter, so a declaration of 'clamp_byte' must be available [-fpermissive]
     ptrOut[4] = clamp_byte((128 + 298 \* c - 100 \* d - 208 \* e) >> 8); // green
                                                                    ^
src/image.cpp:476:58: error: there are no arguments to 'clamp_byte' that depend on a template parameter, so a declaration of 'clamp_byte' must be available [-fpermissive]
     ptrOut[5] = clamp_byte((128 + 298 \* c + 516 \* d) >> 8); // blue
                                                          ^
src/image.cpp: In function 'void rsimpl::deproject_z(float_, const rs_intrinsics&, const uint16_t_, float)':
src/image.cpp:486:98: error: 'deproject_depth' was not declared in this scope
         deproject_depth(points, z_intrin, z_pixels, [z_scale](uint16_t z) { return z_scale \* z; });
                                                                                                  ^
src/image.cpp: In function 'void rsimpl::deproject_disparity(float_, const rs_intrinsics&, const uint16_t_, float)':
src/image.cpp:491:146: error: 'deproject_depth' was not declared in this scope
         deproject_depth(points, disparity_intrin, disparity_pixels, [disparity_scale](uint16_t disparity) { return disparity_scale / disparity; });
                                                                                                                                                  ^
make: **\* [obj/image.o] Error 1

Thanks

**Comment by jetsonhacks** [comment]
Yes, it looks like they added commits to a tagged version. 
An important Git guideline is Never(*) modify commits that you have published.
The tags aren't meant to be mutable. 
But anyway, I'll have to go back and come up with a work around.

**Comment by jetsonhacks** [comment]
Have a go at the latest version.

**Comment by vftejada** [comment]
Now I got the same glfw compile error reported on issue #2

**Comment by jetsonhacks** [comment]
Are you running 64 bit L4T?

**Comment by vftejada** [comment]
Yes but I'm going to give it a try on 32 bit as well

**Comment by jetsonhacks** [comment]
Please use the version in the repository for the TX1:

https://github.com/jetsonhacks/installLibrealsenseTX1
