### ISSUE TITLE
glfw compile error on jetson tx1 L4T 24.1

### ISSUE THREAD

**Issue by sclin-loauas** [jetsonhacks/installLibrealsense#2]
I tried to install librealsense on jetson tx1 using 'installLibrealsenseUVC.sh' shell file. Some link errors show up when compiling glfw. The errors are like this:
libGL.so: undefined reference to 'drm......

I have searched some similar issues in the github page of librealsense. It seems like the problem is related to the NVIDIA driver on PC. But I have flashed the system with jetpack. Do I need to install the driver manuelly?

**Comment by jetsonhacks** [comment]
Are you running 64 bit L4T? L4T 64 it has issues with the soft link for libGL.so and the MESA library. One fix is: 

cd /usr/lib/aarch64-linux-gnu
sudo rm libGL.so
sudo ln -s /usr/lib/aarch64-linux-gnu/tegra/libGL.so libGL.so

**Comment by sclin-loauas** [comment]
@jetsonhacks 
I am running 64 bit L4T. But it is the same on 32 bit L4T. Your solution fixed the glfw issue on both systems. 
But another issue shows up while I continuing installation. I use installLibrealsenseUVC.sh shell file. The lib and examples are compiled correctly. But when I plug in R200 and start cpp-config-ui, the program crashes and throws an error message:
uvc_set_ctrl(...) returned LIBUSB_ERROR_PIPE

**Comment by jetsonhacks** [comment]
Have you tried running the example with sudo? It could be that when the script aborted the udev rules did not get put into place. Also, are you plugging into the USB port, or into a hub. If using a 3.0 hub, is it powered?

**Comment by sclin-loauas** [comment]
I have tried sudo command which outputs the same error message. And I plugged into the USB 3.0 port of tx1 develop kit.

**Comment by vftejada** [comment]
Got the same error running the example with sudo and R200 directly plugged into USB 3.0

**Comment by sclin-loauas** [comment]
The problem is solved. However I do not know why. I tried another fork of librealsense https://github.com/Maghoumi/librealsense.
It does not work at first. But It goes well after I unplug and plug in the camera several times.

**Comment by vftejada** [comment]
I haven't tried any other fork but  I managed to successfully run all the examples plugging an unplugging the camera several times as well. I remembered I had the same kind of issues with the previous Jetpack

**Comment by jetsonhacks** [comment]
For the TX1, please use the repository:
https://github.com/jetsonhacks/installLibrealsenseTX1
